### ISSUE TITLE
throw error

### ISSUE THREAD

**Issue by KNGRSM** [asdqwex/discobot#107]
/usr/local/lib/node_modules/discobot/node_modules/table/dist/validateTableData.js:38
        throw new Error('Table must define at least one row.');
              ^

any help with this?

**Comment by asdqwex** [comment]
Would you attach the full log output of the bot session? A little more context is needed.

**Comment by erulabs** [comment]
Strange - `table` is required as a lib in `package.json`, but I dont see it being used anywhere. I think this was my mistake? I used `table` in my help_text branch. Not sure how it got here.

Anyways, since it's not being used in master branch - my guess is @KNGRSM is using an old release (run `npm install -g discobot@0.0.20` to get the current version) or our current release (0.0.20) is old and bad :P 

Mind letting us know which version you've got installed? The output of `fgrep version /usr/local/lib/node_modules/discobot/package.json` should give us what we need :)

**Comment by asdqwex** [comment]
Assumed fixed until further notice. Thank you for submitting your bug. Let us know if there is anything else we can help with.
